huh_encore:
  encore:
    entries:
      - { name: "contao-parallaximage-bundle", requiresCss: true, file: "vendor/heimrichhannot/contao-parallaximage-bundle/src/Resources/assets/js/contao-parallaximage-bundle.js"}
    legacy:
      js:
        - huh.contao-parallaximage-bundle
      css:
        - huh.contao-parallaximage-bundle