services:
  huh.parallaximage.listener.hooks:
    class: HeimrichHannot\ContaoParallaxImageBundle\EventListener\HookListener
    public: true
    autowire: true

  HeimrichHannot\ContaoParallaxImageBundle\Asset\FrontendAsset:
    autowire: true